"""initial employee table

Revision ID: 088f9b98f737
Revises: 
Create Date: 2026-10-07 13:46:38.717430
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '088f9b98f737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeeDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employeeDetails_email'), 'employeeDetails', ['email'], unique=True)
    op.create_index(op.f('ix_employeeDetails_employee_code'), 'employeeDetails', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employeeDetails_id'), 'employeeDetails', ['id'], unique=False)
    op.create_index(op.f('ix_employeeDetails_name'), 'employeeDetails', ['name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employeeDetails_name'), table_name='employeeDetails')
    op.drop_index(op.f('ix_employeeDetails_id'), table_name='employeeDetails')
    op.drop_index(op.f('ix_employeeDetails_employee_code'), table_name='employeeDetails')
    op.drop_index(op.f('ix_employeeDetails_email'), table_name='employeeDetails')
    op.drop_table('employeeDetails')
    # ### end Alembic commands ###
